//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Nufus
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Yıl giriniz.")]
        [Display(Name = "Nüfus Dağılım Yılı:")]
        public int Yil { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz.")]
        [Display(Name = "Bozüyük Nüfus:")]
        public int Bozuyuk { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz.")]
        [Display(Name = "Gölpazarı Nüfus:")]
        public int Golpazari { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz.")]
        [Display(Name = "İnhisar Nüfus:")]
        public int Inhisar { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz.")]
        [Display(Name = "Merkez Nüfus:")]
        public int Merkez { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz.")]
        [Display(Name = "Osmaneli Nüfus:")]
        public int Osmaneli { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz.")]
        [Display(Name = "Pazaryeri Nüfus:")]
        public int Pazaryeri { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz.")]
        [Display(Name = "Söğüt Nüfus:")]
        public int Sogut { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz.")]
        [Display(Name = "Yenipazar Nüfus:")]
        public int Yenipazar { get; set; }
    }
}
