//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Resimler
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "lütfen resim seçiniz.")]
        [Display(Name = "Resim:")]
        public string Link { get; set; }
    }
}
