//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TuristikYer
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Turistik yerin adını yazınız.")]
        [Display(Name ="Turistik Yer:")]
        public string TuristikYer1 { get; set; }
        [Required(ErrorMessage = "Turistik yerin kısaca açıklamasını yazınız.")]
        [Display(Name = "Açıklama:")]
        public string Aciklama { get; set; }
    }
}
